### ISSUE TITLE
Issue with schedules on android / SDK behaviour is different for iOS and android

### ISSUE THREAD

**Issue by rohit-fareye** [surveysparrow/surveysparrow-react-native-sdk#13]
There is an issue in android, Initially on scheduling a survey with the parameters mentioned below - 

`scheduleSurveySparrow({
                    domain: 'xyz',
                    token: 'xyz',
                    surveyType: 'classic',
                    startAfter: 0,
                    repeatInterval: 30000,
                    repeatSurvey: false,
                    customParams: [
                      { name: 'email', value: 't@t.com' },
                    ],
                    thankYouPageTimeLimit: 3000
                  })`

On successful submission in onSurveyResponseListener, I clear the schedule by using clearSurveySparrow method. Now, I am creating a new schedule with the parameters -
`scheduleSurveySparrow({
                      domain: 'xyz',
                      token: 'xyz,
                      surveyType: 'classic',
                      startAfter: 240000,
                      repeatInterval: 30000,
                      repeatSurvey: true,
                      customParams: [
                        { name: 'email', value: 't@t.com' },
                      ],
                    });`

Now because the startAfter is set to 4 minutes in this , the alert should not appear before that but on the second call to above method. Alert gets shown. 

This is working as expected on iOS and we are able to execute our use case but on android it is not working.

**Comment by rohit-fareye** [comment]
Any update on this?

**Comment by sachin-kumar56** [comment]
@rohit-fareye we have started to investigate this issue can you help us with the further details mentioned below 
1) react native version
2) android minSDKversion
3) surveysparrow-react-native-sdk version
cc: @hemanath-ss

**Comment by rohit-fareye** [comment]
react-native -> 0.70.5
android minSDKversion -> 21
surveysparrow-react-native-sdk version -> 0.1.3

**Comment by sachin-kumar56** [comment]
@rohit-fareye we have fixed the issue mentioned above in the 0.1.4 version of our SDK can you install the recent version and check it
