### ISSUE TITLE
Android - Crash on screen rotation

### ISSUE THREAD

**Issue by rohit-fareye** [surveysparrow/surveysparrow-react-native-sdk#17]
After launch of survey sparrow webview, on screen rotation it crashes the application on android. We have set the screen orientation to portrait for our application but even if we allow the app rotation according to phone orientation, it still crashes the app.

What is expected - We have locked the screen orientation to portrait for our app. Survey sparrow must not allow rotation too.

**Comment by sachin-kumar56** [comment]
hi, @rohit-fareye can I know what react-native SDK version you are using?
cc: @hemanath-ss

**Comment by rohit-fareye** [comment]
RN version - 0.70.5
surveysparrow-react-native-sdk version - 0.1.5

**Comment by sachin-kumar56** [comment]
@rohit-fareye kindly check the latest version ( 0.1.6 ) of the SDK
cc: @hemanath-ss
