### ISSUE TITLE
iOS App Crash on survey submission

### ISSUE THREAD

**Issue by Subramanyarao11** [surveysparrow/surveysparrow-react-native-sdk#26]
I am experiencing a crash in my iOS application when using the surveysparrow-react-native-sdk. The crash occurs only on iOS devices on survey submission and is traced back to the library code in Xcode. Below are the details of my environment and the issue.  

Machine - MacBook Air M1, Sonoma 14.2
Processor - Apple M1
Memory - 16GB
React Native Version - 0.73.0
surveysparrow-react-native-sdk - 0.1.10 
CocoaPods Version - 1.15.2 
pod used - pod 'SurveySparrowSdk', :git => 'https://github.com/surveysparrow/surveysparrow-ios-sdk.git', :tag => '0.4.5'

Crash Details:
* Crash Log:
    * Thread 1: signal SIGABRT

Steps to Reproduce:   
here is the gist which points to the component that leads to crash => https://gist.github.com/Subramanyarao11/a4d20d05b5c44bcf9f10c0b9ad8c6155

the problem we are facing is once we invoke it, it opens survey in full screen mode as expected and everything works fine however once user submits the survey it crashes as you can see in the attached image  

Expected Behavior
The expected behavior is that after submitting the survey, the app should return to the previous screen without crashing ( working fine in android as expected ).

Additional Information:
* Xcode Version: Version 15.3 (15E204a)
* iOS Version Tested On: 17.4
* Device Models Tested: iPhone 15 Pro Simulator

<img width="1432" alt="Screenshot 2024-10-30 at 11 11 31 PM" src="https://github.com/user-attachments/assets/8d280545-f0e5-4d9b-9756-4ecbb881cde0">

**Comment by Subramanyarao11** [comment]
I've created a minimal reproduction project at https://github.com/Subramanyarao11/survey-sparrow-test  to help diagnose the issue. The project demonstrates the same crash I mentioned above in IOS

**Comment by Gokulkrishna-Raju** [comment]
Fixed the issue and Released a new version [v0.2.0](https://www.npmjs.com/package/surveysparrow-react-native-sdk/v/0.2.0)

**Comment by Gokulkrishna-Raju** [comment]
Thanks @Subramanyarao11  for reporting

> Let us know for further Queries

**Comment by Subramanyarao11** [comment]
@Gokulkrishna-Raju Thank you for checking the issue and fixing it. Just bumped the version and tested it, app is not crashing when we submit, but on submission we are taken to survey sparrow signup page and we don't recieve back any data in the listener
```
 const sub = onSurveyResponseListener.addListener(
      'onSurveyResponse',
      (data: any) => {
        console.log(data);
      },
    );
```
 can you please check this. Thanks

**Comment by Gokulkrishna-Raju** [comment]
@Subramanyarao11, 

Are you using the same Domain and token present in the example repo given above ?

That token is throwing this error
`'survey response from embed survey is', { error: 'Invalid token, generate and use a Mobile SDK token' }`

Can you use a SDK Share token, you will get the response properly.

> Creating SDK Share token: Open a survey -> Go to Share page -> Create SDK Share -> Copy token from it.
