### ISSUE TITLE
What should be the domain name?

### ISSUE THREAD

**Issue by Saad-Bashar** [surveysparrow/surveysparrow-react-native-sdk#4]
I created a survey from the dashboard and used the shareable link "https://socarmy.surveysparrow.com/s/Test---Customer-Satisfaction-Survey/tt-f5ebd2" that was given me after the completion of the survey as the domain name. But the survey loader keeps loading. What am I doing wrong?

**Comment by hemanath-ss** [comment]
Hi @Saad-Bashar, 
1. The domain name is `socarmy.surveysparrow.com`. 

Can you also please make sure you are using the SDK-Share token you generated from the _Survey -> Share -> Mobile SDK_. 
Once you generate this token you can use here, Like
```
<SurveySparrow
  styles={styles.box}
  config={{
    domain: 'socarmy.surveysparrow.com',
    token: '<generated-sdk-share-token>',
    surveyType: 'classic',
    customParams: [
      { name: 'testname', value: 'custom value 10' },
      { name: 'testname2', value: 'custom value 2' },
    ],
  }}
  onSurveyComplete={(data) => {
    console.log('survey response from embed survey is', data);
  }}
/>

**Comment by Saad-Bashar** [comment]
Great, thanks! It worked!
