### ISSUE TITLE
embeeded survey is not showing up in android 

### ISSUE THREAD

**Issue by Saad-Bashar** [surveysparrow/surveysparrow-react-native-sdk#6]
Embedded SurveySparrow component comes fine in iOS but on android, it is just plain white, and nothing loads.

**Comment by hemanath-ss** [comment]
@Saad-Bashar , Can you share more details about this along with the code and output with us?. So it will be easier for us to check it out and get back to you!

**Comment by Saad-Bashar** [comment]
![Screenshot 2021-12-08 at 12 41 02 PM](https://user-images.githubusercontent.com/13269141/145149317-f316881c-075f-446c-ae40-36addbdd0020.png)
Here is the snippet which is working fine for iOS but on android nothing loads, I mean the survey does not show up.

**Comment by sachin-kumar56** [comment]
@Saad-Bashar do you get any error in metro when loading in android ?

**Comment by sachin-kumar56** [comment]
@Saad-Bashar can you add style props to the SurveySparrow component with the height and width that you want for example : 
<SurveySparrow
          styles={{
            width: '100%',
            height: 500,
          }}
          config={{
            domain: 'socarmy.surveysparrow.com',
            token: 'tt-446ec5',
            surveyType: 'classic',
          }}
          onSurveyComplete={data => {
            console.log('survey response from embed survey is', data);
          }}
        />

**Comment by Saad-Bashar** [comment]
No error :( I tried to set the styling as well but still the same.

**Comment by Saad-Bashar** [comment]
Hey I just tried again with styles and its working! Thanks!
