### ISSUE TITLE
Submit survey programmaticaly

### ISSUE THREAD

**Issue by qduborper** [surveysparrow/surveysparrow-react-native-sdk#7]
Hi ! thanks for this library
I've one question about embedded integration. Is it possible to hide the submit button from the webview + integrate a react native button / behavior in order to trigger survey sparrow submission ? This is for having a seamless integration with our existing react native UI and flow

Best regards

**Comment by sachin-kumar56** [comment]
hi @qduborper auto-submit feature is available in our chat survey you can go to survey settings and can configure it and as far as having a button for submitting the survey you can expect that in our next update thank you
