### ISSUE TITLE
Expo Support?

### ISSUE THREAD

**Issue by vinayn-mend** [surveysparrow/surveysparrow-react-native-sdk#8]
Does this support Expo managed project?

**Comment by sachin-kumar56** [comment]
hi @vinayn-mend right now surveysparrow-react-native-sdk is not supported in expo managed workflow since expo does not allow libraries to have custom native components in their managed workflow

**Comment by vinayn-mend** [comment]
@sachin-kumar56 Is there any alternative to integrate NPS survey to an Expo managed work ? Any idea?

**Comment by sachin-kumar56** [comment]
@vinayn-mend one way would be to create custom survey components like rating and text questions and use our APIs for submission or you can eject from expo to convert from managed workflow to bare workflow

**Comment by sachin-kumar56** [comment]
@vinayn-mend you can use react native webview package (https://www.npmjs.com/package/react-native-webview) and can pass the survey uri example: <WebView source={{ uri: 'https://sample.surveysparrow.com/s/ccvb/tt-d8b4ba' }} />
